# -*- coding: utf-8 -*-
"""end-to-end-ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qoVj0X9LK8Luv3PAILM8Cwarve3BgEh
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pickle
import sklearn

print("numpy",np.__version__)
print("pandas",pd.__version__)
print("sklearn",sklearn.__version__)

"""**Load the Data**"""

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/placement.csv')
df

df.head()

"""**Preprocessing**

"""

df.info()

df.shape

df= df.iloc[:,1:]
df

"""**EDA**"""

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

"""**FeatureSelection** - ignore because by toy data set

**Select input and output cols**
"""

x=df.iloc[:,0:2]
y=df.iloc[:,-1]

x

y

"""**Train Test Split**"""

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.1)

X_train

Y_train

X_test

Y_test

"""**Scale the Value**"""

from sklearn.preprocessing import StandardScaler

Scaler = StandardScaler()

X_train = Scaler.fit_transform(X_train)

X_train

X_test = Scaler.transform(X_test)

X_test

"""***Call Logistic Regression***

"""

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

"""**Model training**"""

clf.fit(X_train,Y_train)

Y_pred = clf.predict(X_test)
Y_pred

Y_test

"""**Accuracy Score**"""

from sklearn.metrics import accuracy_score

accuracy_score(Y_test,Y_pred)

"""**Making decision Boundary**"""

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X_train,Y_train.values,clf=clf , legend = 2)



"""**call library**"""

import pickle

pickle.dump(clf,open('model.pkl','wb'))



"""**deploy model** - HEROKU , aws activate , google cloud"""

